# Generated by Django 5.1 on 2024-10-27 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_update'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Update',
        ),
    ]
